apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: master-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  #volumeName: pvc-0d5e489e-3866-4c61-90fe-2f3605a6c22e
  storageClassName: gp2
  volumeMode: Filesystem